### ISSUE TITLE
Look into Axios functionality

### ISSUE THREAD

**Issue by StuvaScript** [Code-the-Dream-School/hh-team1-front#25]
Look into how to properly implement Axios CRUD functionality. Also investigate how to manage Headers.

**Comment by AmandaHockmuth** [comment]
I thought you might find this interesting (even though its Node focused) I am researching axios a little more today [here](https://www.youtube.com/watch?v=3KstYwmHd1U) and [here](https://www.youtube.com/watch?v=OFWATycG_Wc)
